volumes:
  ydb-data:
    # driver: local
    # driver_opts:
    #   type: tmpfs
    #   device: tmpfs
    #   o: size=80g
  ydb-certs:

services:
  sdk:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: sdk

    volumes:
      - ydb-certs:/ydb_certs
      - ../:/workspaces/ydb-go-sdk:cached

    environment:
      - YDB_VERSION=24.3
      - YDB_CREDENTIALS_USER=root
      - YDB_CREDENTIALS_PASSWORD=1234
      - YDB_CONNECTION_STRING=grpc://ydb:2136/local
      - YDB_CONNECTION_STRING_SECURE=grpcs://ydb:2135/local
      - YDB_SSL_ROOT_CERTIFICATES_FILE=/ydb_certs/ca.pem

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  ydb:
    image: ghcr.io/ydb-platform/local-ydb:24.3
    restart: unless-stopped
    hostname: ydb
    platform: linux/amd64

    volumes:
      - ydb-data:/ydb_data
      - ydb-certs:/ydb_certs

    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765

  prometheus:
    image: prom/prometheus:v3.3.0
    restart: unless-stopped
    hostname: prometheus
    platform: linux/amd64

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ydb-certs:/ydb_certs

    ports:
      - 9090:9090
